In [1]:
!pip install numpy


[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [ ]:
## Create array using numpy
# Create 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1) # -> Simply print array
print(type(arr1)) # -> type of arr1
print(arr1.shape) # -> usually print the shape of array

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # -> Means 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [4]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [7]:
## 2D array
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


# In-Build Functions

In [ ]:
np.arange(0,10,2).reshape(5,1) #->Create a sequence with a step

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
np.ones((3,4)) #-> create array filled with ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(3) #-> create identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Attributes of Numpy
arr = np.array([[1,2,3,4],[5,6,7,8]])

print("Array : \n",arr)
print("Shape : ",arr.shape)
print("Number of Dimensions : ",arr.ndim)
print("Size (numbers of elemets ): ",arr.size)
print("Data type : ",arr.dtype)
print("Item size(in bytes) : ",arr.itemsize)

Array : 
 [[1 2 3 4]
 [5 6 7 8]]
Shape :  (2, 4)
Number of Dimensions :  2
Size (numbers of elemets ):  8
Data type :  int64
Item size(in bytes) :  8


# Numpy Vectorized Operation

In [13]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

# Elements wise addition
print("Addition : ",arr1+arr2)

# Elements wise Subtraction
print("Addition : ",arr1-arr2)

# Elements wise Multiplication
print("Addition : ",arr1*arr2)

# Elements wise Division
print("Addition : ",arr1/arr2)

Addition :  [11 22 33 44 55]
Addition :  [ -9 -18 -27 -36 -45]
Addition :  [ 10  40  90 160 250]
Addition :  [0.1 0.1 0.1 0.1 0.1]


# Universal Functions of Numpy

In [15]:
arr = np.array([2,3,4,5,6])

# Square root
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

#natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


# Array Slicing and Indexing

In [16]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array : \n",arr)

Array : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
arr[1]

array([4, 5, 6])

In [18]:
arr[0][2]

np.int64(3)

In [19]:
arr[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [20]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [21]:
# Modify array elements
arr[0][0] = 100
print(arr)

[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [22]:
arr[1:] = 100
print(arr)

[[100   2   3]
 [100 100 100]
 [100 100 100]]


# Statistical concept - Normalization

In [24]:
data = np.array([2,3,4,5,6])
print("Data : ",data)

# Calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize
normalize_data = (data-mean)/std_dev
print("Normalize data : ",normalize_data)


Data :  [2 3 4 5 6]
Normalize data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [25]:
#Mean
print("Mean : ",np.mean(data))

#Median
print("Median : ",np.median(data))

#Standard Deviation
print("Standard Deviation : ",np.std(data))

#Variance
print("Variance : ",np.var(data))


Mean :  4.0
Median :  4.0
Standard Deviation :  1.4142135623730951
Variance :  2.0


# Logical Operation

In [27]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

data[data>5]

array([ 6,  7,  8,  9, 10])

In [28]:
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [6]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])

In [7]:
data[(data>5) | (data<=8)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])